version: '3'

services:
  haproxy:
    build: ./haproxy/.
    ports:
     - '8080:8080'

  piping-1: &piping_settings
    image: nwtgck/piping-server:v0.8.4
    command: --http-port=80

  piping-2:
    <<: *piping_settings

  piping-3:
    <<: *piping_settings

  piping-4:
    <<: *piping_settings
