version: '3'

services:
  haproxy:
    image: haproxy:2.0.5-alpine
    ports:
     - '8080:8080'
    depends_on:
     - piping1
     - piping2
     - piping3
     - piping4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  piping1: &piping_settings
    image: nwtgck/piping-server:v0.14.0
    command: --http-port=80

  piping2:
    <<: *piping_settings

  piping3:
    <<: *piping_settings

  piping4:
    <<: *piping_settings
